<?php
if (!defined ('in')) exit ();
$UpdateTSPK = '0012014040601';
$queries = array (
	"ALTER TABLE `{$prefix}_config` CHANGE COLUMN `nazov` `nazov` VARCHAR(255) NOT NULL, ADD PRIMARY KEY (`nazov`), ADD UNIQUE INDEX `nazov_UNIQUE` (`nazov` ASC);",
	"ALTER TABLE `{$prefix}_apps` CHANGE COLUMN `fname` `fname` VARCHAR(255) NOT NULL, ADD UNIQUE INDEX `fname` (`fname` ASC), ADD INDEX `allowed` (`allowed` ASC), ADD INDEX `appMode` (`application` ASC), ADD INDEX `widgetMode` (`widget` ASC), ADD INDEX `hcmMode` (`hcm` ASC), ADD INDEX `pluginMode` (`plugin` ASC), ADD INDEX `staticMode` (`static` ASC), ADD INDEX `position` (`position` ASC);",
	"ALTER TABLE `{$prefix}_cats` CHANGE COLUMN `skr` `skr` VARCHAR(255) NOT NULL, ADD UNIQUE INDEX `seoTitle` (`skr` ASC), ADD INDEX `showing` (`showing` ASC), ADD INDEX `inMenu` (`inmenu` ASC), ADD INDEX `position` (`position` ASC);",
	"ALTER TABLE `{$prefix}_clanky` CHANGE COLUMN `nadpis` `nadpis` VARCHAR(255) NOT NULL, CHANGE COLUMN `seo` `seo` VARCHAR(255) NOT NULL, CHANGE COLUMN `tags` `tags` VARCHAR(255) NULL DEFAULT NULL, ADD INDEX `autor` (`autor` ASC), ADD INDEX `nadpis` (`nadpis` ASC), ADD INDEX `seoTitle` (`seo` ASC), ADD INDEX `createTime` (`added` ASC), ADD INDEX `category1` (`cat` ASC), ADD INDEX `category2` (`cat2` ASC), ADD INDEX `category3` (`cat3` ASC), ADD INDEX `showing` (`showing` ASC), ADD INDEX `confirmed` (`confirmed` ASC), ADD INDEX `readCount` (`reads` ASC), ADD INDEX `tags` (`tags` ASC);",
	"ALTER TABLE `{$prefix}_comments` CHANGE COLUMN `kde` `kde` VARCHAR(255) NOT NULL, CHANGE COLUMN `autor` `autor` VARCHAR(255) NOT NULL, CHANGE COLUMN `ip` `ip` VARCHAR(255) NOT NULL, ADD INDEX `kde` (`kde` ASC), ADD INDEX `autor` (`autor` ASC), ADD INDEX `createTime` (`added` ASC), ADD INDEX `ip` (`ip` ASC);",
	"ALTER TABLE `{$prefix}_download` CHANGE COLUMN `file` `file` VARCHAR(255) NOT NULL, ADD INDEX `hits` (`hits` ASC), ADD INDEX `file` (`file` ASC), ADD INDEX `size` (`size` ASC);",
	"ALTER TABLE `{$prefix}_gall` CHANGE COLUMN `skr` `skr` VARCHAR(255) NOT NULL, ADD INDEX `autor` (`autor` ASC), ADD INDEX `seoTitle` (`skr` ASC), ADD INDEX `showing` (`showing` ASC);",
	"ALTER TABLE `{$prefix}_hits` CHANGE COLUMN `ip` `ip` VARCHAR(255) NOT NULL, CHANGE COLUMN `kde` `kde` VARCHAR(255) NOT NULL, CHANGE COLUMN `browser` `browser` VARCHAR(255) NOT NULL, ADD INDEX `ip` (`id` ASC),ADD INDEX `kde` (`kde` ASC), ADD INDEX `kedy` (`kedy` ASC), ADD INDEX `browser` (`browser` ASC);",
	"ALTER TABLE `{$prefix}_img` ADD INDEX `type` (`type` ASC), ADD INDEX `album` (`cat` ASC), ADD INDEX `createTime` (`added` ASC);",
	"ALTER TABLE `{$prefix}_iplog` CHANGE COLUMN `ip` `ip` VARCHAR(255) NOT NULL, CHANGE COLUMN `what` `what` VARCHAR(255) NOT NULL, CHANGE COLUMN `hodnota` `hodnota` VARCHAR(255) NOT NULL, ADD INDEX `ip` (`ip` ASC), ADD INDEX `what` (`what` ASC), ADD INDEX `hodnota` (`hodnota` ASC);",
	"ALTER TABLE `{$prefix}_menu` ADD INDEX `post` (`post` ASC), ADD INDEX `jetobox` (`jetobox` ASC), ADD INDEX `kdeje` (`kdeje` ASC);",
	"ALTER TABLE `{$prefix}_microblog` ADD INDEX `autor` (`autor` ASC), ADD INDEX `createTime` (`added` ASC);",
	"ALTER TABLE `{$prefix}_moderators` CHANGE COLUMN `nick` `nick` VARCHAR(255) NOT NULL, CHANGE COLUMN `password` `password` VARCHAR(255) NOT NULL, CHANGE COLUMN `statichash` `statichash` VARCHAR(255) NULL DEFAULT NULL, CHANGE COLUMN `mail` `mail` VARCHAR(255) NULL DEFAULT NULL, ADD INDEX `nick` (`nick` ASC), ADD INDEX `password` (`password` ASC), ADD INDEX `staticHash` (`statichash` ASC), ADD INDEX `isadmin` (`isadmin` ASC), ADD INDEX `blocked` (`blocked` ASC), ADD INDEX `needConfirm` (`needConfirm` ASC);",
	"ALTER TABLE `{$prefix}_polls` ADD INDEX `autor` (`autor` ASC), ADD INDEX `locked` (`locked` ASC);",
	"ALTER TABLE `{$prefix}_sec` CHANGE COLUMN `seo` `seo` VARCHAR(255) NOT NULL, ADD UNIQUE INDEX `seo_UNIQUE` (`seo` ASC), ADD INDEX `msec` (`msec` ASC);",
	"ALTER TABLE `{$prefix}_visits` CHANGE COLUMN `ip` `ip` VARCHAR(15) NOT NULL, CHANGE COLUMN `browser` `browser` VARCHAR(240) NOT NULL, ADD INDEX `visitFinding` (`browser` ASC, `ip` ASC), ADD INDEX `ip` (`ip` ASC), ADD INDEX `visitTime` (`kedy` DESC);",
);